apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: main-collector
  namespace: opentelemetry-operator-system
spec:
  mode: daemonset
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:

      # # Data sources: logs
      # fluentforward:
      #   endpoint: 0.0.0.0:8006

      # # Data sources: metrics
      # hostmetrics:
      #   scrapers:
      #     cpu:
      #     disk:
      #     filesystem:
      #     load:
      #     memory:
      #     network:
      #     process:
      #     processes:
      #     swap:

      # # Data sources: traces
      # jaeger:
      #   protocols:
      #     grpc:
      #     thrift_binary:
      #     thrift_compact:
      #     thrift_http:

      # # Data sources: traces
      # kafka:
      #   protocol_version: 2.0.0

      # # Data sources: traces, metrics
      # opencensus:

      # Data sources: traces, metrics, logs

      # # Data sources: metrics
      # prometheus:
      #   config:
      #     scrape_configs:
      #       - job_name: "otel-collector"
      #         scrape_interval: 5s
      #         static_configs:
      #           - targets: ["localhost:8888"]

      # # Data sources: traces
      # zipkin:

    processors:

    exporters:
      logging:

    service:
      # extensions: [health_check,pprof,zpages]
      pipelines:
        traces:
          receivers: [otlp]
          processors: []
          exporters: [logging]
        metrics:
          receivers: [otlp]
          processors: []
          exporters: [logging]
        logs:
          receivers: [otlp]
          processors: []
          exporters: [logging]
