root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
bin = "./bin/shipping"
cmd = "go build -v -o ./bin/shipping src/main.go"
delay = 1000
exclude_dir = []
exclude_file = []
exclude_regex = []
exclude_unchanged = false
follow_symlink = false
full_bin = ""
include_dir = ["src"]
include_ext = ["go"]
kill_delay = "0s"
log = "build-errors.log"
send_interrupt = false
stop_on_error = true

[color]
app = ""
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[log]
time = false

[misc]
clean_on_exit = false

[screen]
clear_on_rebuild = false
