---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: notification
  name: notification
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification
  template:
    metadata:
      labels:
        app: notification
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "notification"
        dapr.io/app-port: "8080"
    spec:
      containers:
      - name: notification
        image: default-registry:5432/notification:1.0.0
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        securityContext:
          allowPrivilegeEscalation: false
        imagePullPolicy: Always
